vim.g.mapleader = ' '
local set = vim.keymap.set
set('n', '<leader>uu', ':UndotreeToggle<CR>')
set('n', 'Q', '@q')
set('n', '<C-s>', ':w!<CR>')
set('v', '<C-s>', ':w!<CR>')
set('i', '<C-s>', '<esc>:w!<CR>')
set('n', 'Y', 'y$')
set('v', '<leader>p', '\"_dP')
set('v', '<leader>P', '\"_dp')
set('n', '<C-i>', '<C-p>')
set('n', '<Tab>', '>>')
set('n', '<S-Tab>', '<<')
set('v', '<Tab>', '>><esc>gv')
set('v', '<S-Tab>', '<<<esc>gv')
set('n', '<leader>h', ':set hlsearch! hlsearch?<CR>')
set('n', 'n', 'nzzzv')
set('n', 'N', 'Nzzzv')
set('n', 'S', '')
set('v', 'S', '')
set('v', 'S`', 'c`<C-R>"`<Esc>')
set('v', 'S\'', 'c\'<C-R>"\'<Esc>')
set('v', 'S"', 'c"<C-R>""<Esc>')
set('v', 'S[', 'c[<C-R>"]<Esc>')
set('v', 'S]', 'c[<C-R>"]<Esc>')
set('v', 'S{', 'c{<C-R>"}<Esc>')
set('v', 'S}', 'c{<C-R>"}<Esc>')
set('v', 'S(', 'c(<C-R>")<Esc>')
set('v', 'S)', 'c(<C-R>")<Esc>')
set('v', 'S<', 'c<<C-R>"><Esc>')
set('v', 'S>', 'c<<C-R>"><Esc>')
set('c', 'w!!', 'execute \'silent! write !sudo tee % >/dev/null\' <bar> edit!<CR>')
set('n', '<C-j>', 'J')
set('v', 'J', ':m \'>+1<CR>gv=gv')
set('v', 'K', ':m \'<-2<CR>gv=gv')
set('n', 'J', ':m .+1<CR>==')
set('n', 'K', ':m .-2<CR>==')
set('n', '<C-h>', ':BufferLineCyclePrev<CR>')
set('n', '<C-l>', ':BufferLineCycleNext<CR>')
set('n', '<A-h>', ':BufferLineMovePrev<CR>')
set('n', '<A-l>', ':BufferLineMoveNext<CR>')
set('n', '<leader>ss', ':%s///gc<Left><Left><Left>')
set('v', '<leader>ss', 'y:%s/<C-R>"/<C-R>"/gc<Left><Left><Left>')
set('n', '<leader>sc', ':lua vim.lsp.buf.rename()<CR>')
set('v', '<leader>sc', ':lua vim.lsp.buf.rename()<CR>')
set('v', '<C-f>', '"1y0/<C-r>1<CR>')
set('n', '<C-q>', ':bd!<CR>', { silent = true })
set('n', '<leader>gt', 'gg<S-v><S-g>>gv<<C-o>') -- GODOT retab
