xrdb ~/.Xresources
xsetroot -cursor_name left_ptr &
#lxsession &
numlockx &
setxkbmap -option caps:escape &
nitrogen --restore &
check_from_updates.sh
dunst &
picom &
trayer --monitor 2 --edge top --align right --widthtype request --padding 10 --iconspacing 5 --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x2B2E37  --height 26 --distance 5 &
nm-applet &
blueman-applet &
volumeicon &
#/usr/bin/greenclip daemon &
/opt/urserver/urserver --daemon &

exec xmonad
