xrdb ~/.Xresources
xsetroot -cursor_name left_ptr &
#lxsession &
numlockx &
setxkbmap -option caps:escape us,gr &
nitrogen --restore &
check_from_updates.sh
dunst &
picom &
nm-applet &
blueman-applet &
volumeicon &
/opt/urserver/urserver --daemon &

exec xmonad
