require("lspkind").init {
  with_text = true,
  maxwidth = 50,
  symbol_map = {
    Interface = "ﰮ",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "了",
    Color = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "ﰠ",
    Variable = "",
    Class = "ﴯ",
    Keyword = "",
    Snippet = "",
    File = "",
    Reference = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    TypeParameter = ""
  },
}
